name: 🎨 Art Credit Report
description: Report if your artwork is being used without proper credit or permission.
labels: ["art"]
assignees: ["emeraldvoid"]
body:
  - type: markdown
    attributes:
      value: |
       Thank you for reaching out. This form is intended for artists or asset creators who believe their work is being used in Pokémon Re:Battle 2 without proper credit, attribution, or permission. Our goal is to address and resolve these issues respectfully and promptly. We sincerely apologize if your work has not been properly credited.

  - type: input
    id: your_name
    attributes:
      label: Your Name / Artist Handle
      placeholder: The name or handle you use when sharing your artwork.
    validations:
      required: true
  - type: textarea
    id: contact_info
    attributes:
      label: Contact Information
      placeholder: |
        Your email, social media, or preferred contact method if you would like direct follow-up.
    validations:
      required: true
  - type: input
    id: asset_name
    attributes:
      label: Name or Description of the Asset(s)
      placeholder: What artwork, sprites, icons, or assets are being used?
  - type: textarea
    id: asset_links
    attributes:
      label: Link to Original Work (if available)
      placeholder: |
       Please provide links to your original art (e.g. DeviantArt, Twitter, portfolio, or file link).