blank_issues_enabled: false
contact_links:
  - name: 💬 Development Blog
    url: https://pokemon-re-battle-2.vercel.app/
    about: Keep up to date with the latest news and updates.
  - name: 📖 Wiki
    url: https://github.com/EmeraldVoid/Pokemon-re-Battle-2/wiki
    about: Check the wiki for guides, FAQs, and documentation.
